### ISSUE TITLE
Questions about lshaped algorithm

### ISSUE THREAD

**Issue by yshao44** [Pyomo/mpi-sppy#155]
is there an indicator for the benders object that tells the user whether it converged or not?

**Comment by jeanpaulwatson** [comment]
The Benders object does take a converger keyword argument, which is the name (optionally) of a Converger class type. It then constructs an instance of that class, and uses the "is_converged" method in the core iterative loop. However, we do not expose the converger object, nor does it persist past the solve loop. That said, it would be a very easy fix to do so.
