### ISSUE TITLE
Some bulleted lists are not rendering correctly on the Read the Docs

### ISSUE THREAD

**Issue by Matthew-Signorotti** [Pyomo/mpi-sppy#206]
Observed on Safari and Firefox. Each bullet appears as its own paragraph. For instance, see the page on the scenario creator function.

**Comment by DLWoodruff** [comment]
Thanks for the heads-up. It renders correctly on github and also (this weird) on the stable version on readthedocs?!? The source rst file seems to be correct, so I will just look again after the next release and see if the problem magically fixes itself. If not, I'm not sure what I will do.
