### ISSUE TITLE
scen_name_list is not truly optional

### ISSUE THREAD

**Issue by Matthew-Signorotti** [Pyomo/mpi-sppy#207]
The parameter `scen_name_list` of `mpisppy.scenario_tree.ScenarioNode.__init__` is said to be optional and no longer used, but cannot have a default value and be followed by positional parameters. Constructing a `ScenarioNode` gives `TypeError: __init__() missing 1 required positional argument: 'scen_name_list'` unless you supply a value. Is there any reason not to change the constructor signature ASAP?

**Comment by bknueven** [comment]
Yes -- in many places in the examples we expect a positional argument of `None` here. That should probably be fixed, however. Ex:
https://github.com/Pyomo/mpi-sppy/blob/fa9056637d02cd2588cfdae2f9a9d7228c96beb9/mpisppy/tests/examples/hydro/hydro.py#L156-L165
