### ISSUE TITLE
RuntimeError: Found infeasible solution which was feasible before

### ISSUE THREAD

**Issue by brentertainer** [Pyomo/mpi-sppy#255]
I am encountering the runtime error from the issue title as the progressive hedging algorithm attempts to terminate. The file below contains the text I see written to the terminal.

[winterization.stdout.txt](https://github.com/Pyomo/mpi-sppy/files/8880483/winterization.stdout.txt)

The particular section of code that raises the error is [here](https://github.com/Pyomo/mpi-sppy/blob/5c6b4b8cd26af517ff09706d11751f2fb05b1b5f/mpisppy/cylinders/spoke.py#L355-L359).

In those lines of code, I see the comment saying "this should be feasible here; if not we've done something wrong". This check was added a little more than a year ago. Have the developers since encountered this issue? Is it possible that the settings I specify are causing this issue?

**Comment by DLWoodruff** [comment]
Yes, we have seen this. It usually occurs during finalization while trying
to compute the objective function for xhat. It may have something to do
with the solver tolerance settings for the xhat spoke versus the hub, but
it could be something else.  Are you using vanilla and baseparsers? If so,
can you send me your command line (to ***@***.***). If not, we
might have to zoom.
  Dave

**Comment by brentertainer** [comment]
First, let me just mention that the log I shared with you is from my Windows system. I experience the same issue on a RHEL7 system with OpenMPI. To keep matters simple, I will only use logs from the RHEL system to avoid confusion.

It's also worth mentioning that I started with serial versions of EF and PH, and those codes are in the attached zip file. For all of serial EF, serial PH, and parallel PH, I observe the solver converging to the same objective value (~31.7153).

@DLWoodruff : Yes, I am using vanilla and baseparsers. I have attached a zip of the files from my project that you need to reproduce the issue. The file `run.sh` is what I use to invoke the Python script with a few baseparser command line options. Inside `main_ph_par.py`, you will see I am also trying to use the NormRhoConverger and NormRhoUpdater.

@bknueven : On the RHEL system, I installed Egret from the main branch of the project. This is evidenced in the attached log. Otherwise, everything you mentioned is accurate. I am unsure what you mean by "complicated" here -- are you alluding to the burden of having to calculate the PTDF matrix for each (scenario, spoke) pair? If not, please elaborate a bit as I am curious to know how you mean it.

Project Files: [three-stage-winterization.zip](https://github.com/Pyomo/mpi-sppy/files/8881274/three-stage-winterization.zip)

Log from RHEL Machine: [winterization.log](https://github.com/Pyomo/mpi-sppy/files/8881277/winterization.log)
