### ISSUE TITLE
Move probability multiplication into numpy

### ISSUE THREAD

**Issue by bknueven** [Pyomo/mpi-sppy#27]
in PHBase.Compute_Xbar

**Comment by DLWoodruff** [comment]
Here's my current thinking on the first steps to help with the issue of differing variables per scenario:

On entry to Compute_Xbar, verify that every local scenario has _PySP_Prob_Mask.
    - If it is not present,  create it and attach it to the scenario.
     - It should be a dictionary of numpy vectors: {ndn: numpy vector of probs} where the numpy vector of probs has the nonant indexes. Note  that ndn = node.name.
      - The values in the dictionary at each node will all be the same: s.PySP\_prob / node.uncond\_prob
 
The loop that creates the local xbar and sqbar should be modified to use this dictionary

IMPORTANT: Users who want to have scenarios with differing Vars per scenario should have created \_PySP\_Prob\_Mask
and attached it to the scenarios in the scenario creation code. They can put zeros in the mask for Vars that
are not really present in the scenario (but are present as dummy auxiliary variables).

**Comment by bknueven** [comment]
One caveat: I think the _PySP_Prob_Mask (or the interface, however we define it) should be a dictionary from `id(var)` to the probability. At the start we can convert it to the appropriate numpy structure.

This way the user need not worry about the arrangement of numpy arrays under-the-hood, and mirrors the rho-setter interface.

**Comment by bknueven** [comment]
Related to changing Compute_Xbar: is it time to remove [this](https://github.com/Pyomo/mpi-sppy/blob/ea0da8a23d3ee4987c98ab5d7eb59357cf1e61f4/mpisppy/phbase.py#L187)?

**Comment by DLWoodruff** [comment]
Yes, it is time to remove the async PH. I think anyone who wants asynch PH should probably just use APH

**Comment by DLWoodruff** [comment]
I agree with your point about the interface.

**Comment by bknueven** [comment]
Closed by #32.
