### ISSUE TITLE
Lagrangian and Lagranger spokes never switch to iterk_solver_options

### ISSUE THREAD

**Issue by tvalenciaz** [Pyomo/mpi-sppy#309]
Both Lagrangian and Lagranger spokes take _iterk_solver_options_ as a configurable option. However, the _iterk_solver_options_, even if configured, are never used.

On the hub, the switch of `opt.current_solver_options` from `opt.iter0_solver_options` to `opt.iterk_solver_options` occurs during the execution of `PHBase.Iter0()`. Since this function is not run on these two bounder spokes, the switch never occurs.
PR forthcoming fixing this.

**Comment by jeanpaulwatson** [comment]
Closed by proximal (temporal) commit, also by Tomas.
