### ISSUE TITLE
Docs website broken?

### ISSUE THREAD

**Issue by atyndall** [Pyomo/mpi-sppy#348]
<img width="1755" alt="Screenshot 2023-11-16 at 8 54 01 am" src="https://github.com/Pyomo/mpi-sppy/assets/1833303/17090166-b846-418f-8b20-5fe3e651a279">

[theme_overrides.css](https://mpi-sppy.readthedocs.io/en/latest/_static/theme_overrides.css) is a 404, so the docs seem a bit messed up?

**Comment by DLWoodruff** [comment]
Thanks for reporting this. Readthedocs has been making some changes lately, so we probably need to do some updates. We will try to get it done this week.

**Comment by bknueven** [comment]
Closed by #351
