### ISSUE TITLE
i need emergency help for pyomo code as financial model as below

### ISSUE THREAD

**Issue by miladaskary** [Pyomo/mpi-sppy#378]
hi dear 
i need to pyomo code for case follow:
my email is: miladaskary@gmail.com

set Investments := STOCKS BONDS ;

param InitialWealth := 55000 ;

param TargetCapital := 80000 ;

param ExcessPerUnitBenefit := 1 ;

param ShortagePerUnitCost := 4 ;

param NumTimes := 3 ;

param Return := 

STOCKS 1 1.06
BONDS  1 1.12

STOCKS 2 1.06
BONDS  2 1.12

STOCKS 3 1.06
BONDS  3 1.12 ;

**Comment by bknueven** [comment]
Not clear this has anything to do with mpi-sppy. To get help from the Pyomo community ask a question on one of the following:
- [Use the #pyomo tag on StackOverflow](https://stackoverflow.com/questions/ask?tags=pyomo)
- [Pyomo Forum](https://groups.google.com/forum/?hl=en#!forum/pyomo-forum)
