### ISSUE TITLE
Create general solution writers

### ISSUE THREAD

**Issue by bknueven** [Pyomo/mpi-sppy#72]
- New user function for `SPBase` called `write_scenario_solution` (like `create_scenario`).
- A new service for Hubs which selects the best incumbent and instructs the associated Spoke `opt` object to call the `write_scenario_solution` function on `SPBase`.
- Default implementation of `write_scenario_solution` which blurts out the Pyomo model (look at PySP)
- Create functionality examples

Some code:
https://github.com/Pyomo/mpi-sppy/blob/47f92599c8d1e6e12511de8e3b42c8d9409a3baa/examples/uc/uc_funcs.py#L200-L245

**Comment by DLWoodruff** [comment]
We also need something that can write the nonant_cache (in either form) to use for MMW

**Comment by bknueven** [comment]
We should create a flag on `SPBase` called `incumbent_available`, which will be `False` by default and set to `True` when an incumbent solution is loaded into the local scenarios.

**Comment by bknueven** [comment]
Closed by #112.
